language: python

compiler: gcc

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# The apt packages below are needed for sphinx builds, which can no longer
# be installed with sudo apt-get.
addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng

os:
    - linux

env:
    global:
        # SET DEFAULTS TO AVOID REPEATING IN MOST CASES
        - CONDA_ARGS='--quiet'
        - CONDA_INSTALL="conda install $CONDA_ARGS"
        - CONDA_CREATE="conda create $CONDA_ARGS"
        - CONDA_DEPS='astropy beautifulsoup4 calcos crds matplotlib nose numpy numpydoc psutil pyyaml scipy sqlalchemy'
        - CONDA_DOC_DEPS="$CONDA_DEPS sphinx"
        - PIP_INSTALL='pip install'
        - SETUP_CMD='test'

matrix:
  include:
    - env: PYTHON_VERSION=3.5
           CRDS_VERSION=6.0

    - env: PYTHON_VERSION=3.6
           # CRDS 6.0 is not available for 3.6, use latest

before_install:

    # USE UTF8 ENCODING. SHOULD BE DEFAULT, BUT THIS IS INSURANCE AGAINST
    # FUTURE CHANGES
    - export PYTHONIOENCODING=UTF8

    # http://conda.pydata.org/docs/travis.html#the-travis-yml-file
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda config --add channels http://ssb.stsci.edu/astroconda

    # Brute update base packages
    - conda update --all -q conda
    - conda info -a

    #CHECK INTERACTIVE MATPLOTLIB BACKENDS
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

install:
    - if [[ -n $ASTROPY_VERSION ]]; then export AP_SELECT="astropy=$ASTROPY_VERSION"; fi
    - if [[ -n $CRDS_VERSION ]]; then export CR_SELECT="crds=$CRDS_VERSION"; fi
    - if [[ -n $NUMPY_VERSION ]]; then export NP_SELECT="numpy=$NUMPY_VERSION"; fi
    - $CONDA_CREATE -n test python=$PYTHON_VERSION $AP_SELECT $NP_SELECT $CR_SELECT $CONDA_DEPS
    - source activate test

    # DOCUMENTATION DEPENDENCIES
    - if [[ $SETUP_CMD == build_sphinx* ]]; then $CONDA_INSTALL numpy=$NUMPY_VERSION $CONDA_DOC_DEPS; fi

script:
   - python setup.py install
   - nosetests
