language: python

compiler: gcc

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# The apt packages below are needed for sphinx builds, which can no longer
# be installed with sudo apt-get.
addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng

os:
    - linux

env:
    global:
        # SET DEFAULTS TO AVOID REPEATING IN MOST CASES
        - CONDA_ARGS='--quiet'
        - CONDA_INSTALL="conda install $CONDA_ARGS"
        - CONDA_CREATE="conda create $CONDA_ARGS"
        - CONDA_DEPS='stsci coverage'
        - CONDA_DOC_DEPS="$CONDA_DEPS sphinx"
        - PIP_INSTALL='pip install'
        - SETUP_CMD='test'
        - COSMO_CONFIG='./tests/cosmoconfig_test.yaml'

matrix:
  include:
    - python: 3.6

before_install:

    # USE UTF8 ENCODING. SHOULD BE DEFAULT, BUT THIS IS INSURANCE AGAINST
    # FUTURE CHANGES
    - export PYTHONIOENCODING=UTF8

    # http://conda.pydata.org/docs/travis.html#the-travis-yml-file
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda config --add channels http://ssb.stsci.edu/astroconda

    # Brute update base packages
    - conda update -q conda
    - conda info -a

install:
    - $CONDA_CREATE -n test python=$TRAVIS_PYTHON_VERSION $AP_SELECT $NP_SELECT $CR_SELECT $CONDA_DEPS
    - source activate test
    - $PIP_INSTALL git+https://github.com/spacetelescope/monitor-framework#egg=monitorframe

    # DOCUMENTATION DEPENDENCIES
    - if [[ $SETUP_CMD == build_sphinx* ]]; then $CONDA_INSTALL numpy=$NUMPY_VERSION $CONDA_DOC_DEPS; fi

    - $PIP_INSTALL codecov
    - $PIP_INSTALL .

script:
   - coverage run -m pytest

after_success:
  - codecov
