name: cos_monitoring
channels:
  - http://ssb.stsci.edu/astroconda
dependencies:
  - numpy>=1.11.1
  - plotly
  - astropy>=1.0.1
  - scipy
  - crds
  - calcos
  - numpydoc
  - pyyaml
  - python>=3.7
  - pytest
  - setuptools
  - pip
  - pip:
      - git+https://github.com/spacetelescope/monitor-framework#egg=monitorframe
      - peewee
      - pyfastcopy
